/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package challenge;

import Models.EmployeesModel;

/**
 *
 * @author Abnet
 */
public class EmployeeUpdate extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePanel
     */
    
    EmployeesModel employee;
    
    public EmployeeUpdate(EmployeesModel emp) {
        this.employee = emp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        GenderCombo = new javax.swing.JComboBox<>();

        setLayout(null);

        jLabel1.setText("image");
        add(jLabel1);
        jLabel1.setBounds(10, 11, 80, 70);

        FirstNameField.setBackground(new java.awt.Color(226, 226, 226));
        FirstNameField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        FirstNameField.setForeground(new java.awt.Color(51, 51, 51));
        FirstNameField.setToolTipText("Enter First Name");
        FirstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(252, 119, 0), 1, true));
        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        add(FirstNameField);
        FirstNameField.setBounds(110, 20, 110, 40);

        LastNameField.setBackground(new java.awt.Color(226, 226, 226));
        LastNameField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LastNameField.setForeground(new java.awt.Color(51, 51, 51));
        LastNameField.setToolTipText("Enter Last Name");
        LastNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(252, 119, 0), 1, true));
        LastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        add(LastNameField);
        LastNameField.setBounds(230, 20, 120, 40);

        EmailField.setBackground(new java.awt.Color(226, 226, 226));
        EmailField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        EmailField.setForeground(new java.awt.Color(51, 51, 51));
        EmailField.setToolTipText("Enter Email Address");
        EmailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(252, 119, 0), 1, true));
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        add(EmailField);
        EmailField.setBounds(360, 20, 120, 40);

        jButton1.setBackground(new java.awt.Color(252, 119, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.setBorder(null);
        add(jButton1);
        jButton1.setBounds(620, 20, 100, 40);

        GenderCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 119, 0)));
        add(GenderCombo);
        GenderCombo.setBounds(490, 20, 110, 40);

//        setBounds(0, 0, 740, 90);
    }// </editor-fold>                        

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> GenderCombo;
    private javax.swing.JLabel jLabel1;
//    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JTextField EmailField;
    // End of variables declaration                   
}
