/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package challenge;

import Models.Entity.EmployeesModel;
import Models.Request.LoginRequest;
import Validations.LoginRequestValidator;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Abnet
 */
public class LoginComponent extends javax.swing.JFrame {

    /**
     * Creates new form LoginComponent
     */
    public LoginComponent() {
        initComponents();
//        /.getScaledInstance(display.getWidth(), display.getHeight(), Image.SCALE_SMOOTH)
        sideImage.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Assets/display_image.png")).getImage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_box = new javax.swing.JTextField();
        password_box = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sideImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management System");
        setSize(new java.awt.Dimension(719, 526));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(2, 17, 21));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign in to your account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 130, 180, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("If you don't have account");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(98, 40, 230, 32);

        email_box.setBackground(new java.awt.Color(226, 226, 226));
        email_box.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        email_box.setForeground(new java.awt.Color(51, 51, 51));
        email_box.setToolTipText("Email Address");
        email_box.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(252, 119, 0), 1, true));
        email_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_boxActionPerformed(evt);
            }
        });
        jPanel1.add(email_box);
        email_box.setBounds(110, 210, 270, 40);

        password_box.setBackground(new java.awt.Color(226, 226, 226));
        password_box.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        password_box.setForeground(new java.awt.Color(51, 51, 51));
        password_box.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(252, 119, 0), 1, true));
        jPanel1.add(password_box);
        password_box.setBounds(110, 300, 270, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 270, 90, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 180, 90, 20);

        jButton1.setBackground(new java.awt.Color(252, 119, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign in");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 370, 270, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 119, 0));
        jLabel5.setText("Create Account");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 40, 130, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 119, 0));
        jLabel6.setText("Forget password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 420, 170, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 119, 0));
        jLabel7.setText("Welcome Back");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 100, 130, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 0, 480, 540);

        sideImage.setText("jLabel8");
        getContentPane().add(sideImage);
        sideImage.setBounds(0, 0, 400, 540);

        setSize(new java.awt.Dimension(897, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void email_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_boxActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Challenge.openRegistrationPage();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        LoginRequest request = new LoginRequest(email_box.getText(), password_box.getText());
        try {
            new LoginRequestValidator().Validate(request);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        
        EmployeesModel employee = Challenge.employee_repo.byEmailAndPassword(request);
        if(employee == null){
            JOptionPane.showMessageDialog(this, "User not found");
            return;
        }
        
        Challenge.lister.initializeList();
        Challenge.openListPage();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginComponent().setVisible(true);
//            }
//        });
        
//        new LoginComponent().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_box;
    private javax.swing.JLabel sideImage;
    // End of variables declaration//GEN-END:variables
}
